version: '3'

services:
  redis:
    container_name: redis
    restart: always
    image: bitnami/redis
    hostname: redis
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=123456
    volumes:
      - ./data/redis:/bitnami/redis/data

  mysql:
    container_name: mysql
    hostname: mysql
    restart: always
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 3306:3306

networks:
  sm:
    driver: bridge
